version: "3.9"
services:
    mongo:
        image: mongo:latest
        restart: always
        container_name: db
        volumes:
          - /data/db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
        ports:
          - "27017:27017"
    sandwiches-after-dark:
        build: .
        environment:
          - MONGODB_URL="mongodb://${MONGODB_ADMIN_USERNAME}:${MONGODB_ADMIN_PASSWORD}@mongo:27017/"
        ports:
          - "8080:8080"
